/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AMapContainer: typeof import('./src/components/AMapContainer.vue')['default']
    DianpinBtn: typeof import('./src/components/DianpinBtn.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    DropUpload: typeof import('./src/components/DropUpload.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Iconify: typeof import('./src/components/Iconify.vue')['default']
    LimitDatePicker: typeof import('./src/components/LimitDatePicker.vue')['default']
    LocationSelector: typeof import('./src/components/LocationSelector.vue')['default']
    MazAvatar: typeof import('maz-ui/components/MazAvatar')['default']
    MazBadge: typeof import('maz-ui/components/MazBadge')['default']
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazCard: typeof import('maz-ui/components/MazCard')['default']
    MazCheckbox: typeof import('maz-ui/components/MazCheckbox')['default']
    MazDialog: typeof import('maz-ui/components/MazDialog')['default']
    MazDrawer: typeof import('maz-ui/components/MazDrawer')['default']
    MazDropdown: typeof import('maz-ui/components/MazDropdown')['default']
    MazFullscreenLoader: typeof import('maz-ui/components/MazFullscreenLoader')['default']
    MazIcon: typeof import('maz-ui/components/MazIcon')['default']
    MazInput: typeof import('maz-ui/components/MazInput')['default']
    MazInputTags: typeof import('maz-ui/components/MazInputTags')['default']
    MazLink: typeof import('maz-ui/components/MazLink')['default']
    MazPicker: typeof import('maz-ui/components/MazPicker')['default']
    MazPopover: typeof import('maz-ui/components/MazPopover')['default']
    MazRadioButtons: typeof import('maz-ui/components/MazRadioButtons')['default']
    MazSelect: typeof import('maz-ui/components/MazSelect')['default']
    MazSpinner: typeof import('maz-ui/components/MazSpinner')['default']
    MazSwitch: typeof import('maz-ui/components/MazSwitch')['default']
    MazTextarea: typeof import('maz-ui/components/MazTextarea')['default']
    MazTransitionExpand: typeof import('maz-ui/components/MazTransitionExpand')['default']
    Quote: typeof import('./src/components/Quote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sketch: typeof import('./src/components/sketch/Sketch.vue')['default']
    SketchItem: typeof import('./src/components/sketch/SketchItem.vue')['default']
    TimePicker: typeof import('./src/components/TimePicker.vue')['default']
    TrafficBtn: typeof import('./src/components/TrafficBtn.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
  export interface ComponentCustomProperties {
    vFullscreenImg: typeof import('maz-ui')['vFullscreenImg']
    vTooltip: typeof import('maz-ui')['vTooltip']
  }
}
