name: Docker Publish on Tag

on:
  push:
    tags:
      - 'v*.*.*' # 只有符合vX.Y.Z格式的标签才会触发此工作流

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker image tags
      id: tag
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
        echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          kwokronny68/roadbook:${{ steps.tag.outputs.version }}
          kwokronny68/roadbook:latest

    - name: Build and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/kwokronny/roadbook:${{ steps.tag.outputs.version }}
          ghcr.io/kwokronny/roadbook:latest