name: Release

on:
  push:
    branches: [ "main" ]
    paths:
      - "packages/roadbook-api/**"
      - "packages/roadbook-vue/**"
      - "Dockerfile"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for fetch all history

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Bump version
        id: bump_version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm version --no-commit-hooks --no-git-tag-version patch
          echo RELEASE=$(node -p -e "require('./package.json').version") >> $GITHUB_ENV

      - name: "Generate Changelog"
        uses: sercanuste/gitmoji-changelog-action@v1
        with:
          commit_message: "📝 Release ${{ env.RELEASE }}"
          add_author: true
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"

      - name: "Create Git Tag"
        run: |
          git tag v${{env.RELEASE}}
          git push origin v${{env.RELEASE}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            kwokronny68/roadbook:${{env.RELEASE}}
            kwokronny68/roadbook:latest
  
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/kwokronny/roadbook:${{env.RELEASE}}
            ghcr.io/kwokronny/roadbook:latest


